In [2]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Scikit-learn imports
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

# Set plotting style
plt.style.use('default')
sns.set_palette("husl")

In [4]:
# Task 1 : Data Loading and Exploration
data_file = "customer_churn_data.csv"
df = pd.read_csv(data_file)

# Display the first few rows of the dataset
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,customer_id,age,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,...,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,customer_satisfaction,support_calls,churn
0,CUST_000001,52,Male,0,Yes,Yes,7,Yes,No,Fiber optic,...,Yes,No,One year,Yes,Electronic check,39.18,294.66,4,3,No
1,CUST_000002,42,Male,0,Yes,No,32,Yes,No,No,...,No internet service,No internet service,One year,Yes,Electronic check,40.36,1286.75,3,1,No
2,CUST_000003,54,Male,0,No,Yes,12,Yes,Yes,Fiber optic,...,Yes,Yes,Month-to-month,No,Bank transfer (automatic),84.77,947.09,2,3,Yes
3,CUST_000004,67,Male,1,No,No,3,Yes,No,DSL,...,No,No,One year,No,Credit card (automatic),54.14,172.76,4,5,No
4,CUST_000005,41,Female,0,Yes,No,7,Yes,No,Fiber optic,...,No,No,Month-to-month,Yes,Electronic check,71.77,466.98,3,3,No

In [5]:
# Display basic information about the dataset
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            10000 non-null  object
 1   age                    10000 non-null  int64
 2   gender                 10000 non-null  object
 3   senior_citizen         10000 non-null  int64
 4   partner                10000 non-null  object
 5   dependents             10000 non-null  object
 6   tenure                 10000 non-null  int64
 7   phone_service          10000 non-null  object
 8   multiple_lines         10000 non-null  object
 9   internet_service       10000 non-null  object
 10  online_security        10000 non-null  object
 11  online_backup          10000 non-null  object
 12  device_protection      10000 non-null  object
 13  tech_support           10000 non-null  object
 14  streaming_tv           10000 non-null  object
 15  streaming_movies       10000 non-null  object
 16  contract               10000 non-null  object
 17  paperless_billing      10000 non-null  object
 18  payment_method         10000 non-null  object
 19  monthly_charges        10000 non-null  float64
 20  total_charges          10000 non-null  float64
 21  customer_satisfaction  10000 non-null  int64
 22  support_calls          10000 non-null  int64
 23  churn                  10000 non-null  object
dtypes: float64(2), int64(5), object(17)
memory usage: 1.8+ MB

In [6]:
# Display Shape
print("Shape of the dataset:")
print(df.shape)

Shape of the dataset:
(10000, 24)

In [7]:
# Check for missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

Missing values in each column:
customer_id              0
age                      0
gender                   0
senior_citizen           0
partner                  0
dependents               0
tenure                   0
phone_service            0
multiple_lines           0
internet_service         0
online_security          0
online_backup            0
device_protection        0
tech_support             0
streaming_tv             0
streaming_movies         0
contract                 0
paperless_billing        0
payment_method           0
monthly_charges          0
total_charges            0
customer_satisfaction    0
support_calls            0
churn                    0
dtype: int64

In [8]:
# Display summary statistics
print("\nSummary statistics of the dataset:")
print(df.describe())

Summary statistics of the dataset:
                age  senior_citizen        tenure  monthly_charges  \
count  10000.000000    10000.000000  10000.000000     10000.000000
mean      44.662500        0.092300     22.216800        53.640204
std       14.397976        0.289463     19.963232        17.047669
min       18.000000        0.000000      1.000000        20.050000
25%       34.000000        0.000000      6.000000        40.407500
50%       44.000000        0.000000     16.000000        51.770000
75%       55.000000        0.000000     33.000000        66.280000
max       80.000000        1.000000     72.000000       111.810000

       total_charges  customer_satisfaction  support_calls
count   10000.000000           10000.000000   10000.000000
mean     1192.146321               3.399300       2.007400
std      1193.960345               1.069193       1.415184
min        20.320000               1.000000       0.000000
25%       306.305000               3.000000       1.000000
50%       796.955000               3.000000       2.000000
75%      1681.077500               4.000000       3.000000
max      7078.800000               5.000000       9.000000